<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use Illuminate\Support\Carbon;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $categories = ['Cultural', 'Literary', 'Education', 'Job & Career', 'Government', 'Music & Entertainment', 'Sports & Fitness', 'Business & Networking', 'Community', 'Food & Lifestyle'];
        $modes = ['offline', 'online', 'hybrid'];
        $areas = ['Boring Road', 'Patliputra', 'Kankarbagh', 'Bailey Road', 'Danapur', 'Gandhi Maidan', 'Rajendra Nagar'];
        $venues = ['Gandhi Maidan', 'Bihar Museum', 'Kalidas Auditorium', 'Ganga Ghat', 'Patna College', 'Hotel Maurya', 'Eco Park'];

        $events = [
            [
                'title' => 'Bihar Sahitya Sammelan 2025',
                'description' => 'Annual literary fest bringing together renowned authors and readers from across Bihar. Experience panel discussions, book launches, and poetry sessions.',
                'event_category' => 'Literary',
                'event_mode' => 'offline',
                'venue' => 'Bihar Museum, Patna',
                'area' => 'Bailey Road',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(12),
                'start_time' => '10:00 AM',
                'end_time' => '06:00 PM',
                'organizer' => 'Bihar Sahitya Mandal',
                'featured_image' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800',
                'price_type' => 'free',
                'interested_count' => 1500,
                'is_featured' => true,
                'is_trending' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Patna Job Fest 2025',
                'description' => 'Mega job fair with 100+ companies recruiting for various positions. Walk-in interviews and career counseling sessions.',
                'event_category' => 'Job & Career',
                'event_mode' => 'hybrid',
                'venue' => 'Hyderabad Gardens, Patna',
                'area' => 'Kankarbagh',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(18),
                'start_time' => '09:00 AM',
                'end_time' => '05:00 PM',
                'organizer' => 'Bihar State Employment Mission',
                'featured_image' => 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800',
                'price_type' => 'free',
                'interested_count' => 3200,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Kavi Sammelan - Kavita Ko Ranag',
                'description' => 'Evening of poetry featuring prominent Hindi and Bhojpuri poets. Open mic for local talent.',
                'event_category' => 'Cultural',
                'event_mode' => 'offline',
                'venue' => 'Kalidas Rangalaya',
                'area' => 'Patna',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(22),
                'start_time' => '06:00 PM',
                'end_time' => '09:00 PM',
                'organizer' => 'Kala Mandir',
                'featured_image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
                'price_type' => 'paid',
                'price' => 100,
                'interested_count' => 850,
                'is_trending' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Bihar Startup Conclave 2025',
                'description' => 'Platform for entrepreneurs to showcase ideas, meet investors, and network with industry leaders.',
                'event_category' => 'Business & Networking',
                'event_mode' => 'offline',
                'venue' => 'Hotel Maurya, Patna',
                'area' => 'Boring Road',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(3),
                'start_time' => '10:00 AM',
                'end_time' => '06:00 PM',
                'organizer' => 'Bihar Industries Association',
                'featured_image' => 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
                'price_type' => 'paid',
                'price' => 500,
                'interested_count' => 620,
                'is_active' => true,
            ],
            [
                'title' => 'India Music Night - Patna',
                'description' => 'Live music performance featuring classical and contemporary Indian music artists.',
                'event_category' => 'Music & Entertainment',
                'event_mode' => 'offline',
                'venue' => 'Eco Park, Rajendra Nagar',
                'area' => 'Rajendra Nagar',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(3),
                'start_time' => '07:00 PM',
                'end_time' => '10:00 PM',
                'organizer' => 'Patna Cultural Society',
                'featured_image' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
                'price_type' => 'paid',
                'price' => 200,
                'interested_count' => 1200,
                'is_active' => true,
            ],
            [
                'title' => 'NEET Guidance Seminar 2025',
                'description' => 'Expert guidance for medical entrance preparation. Tips from top rankers and mentors.',
                'event_category' => 'Education',
                'event_mode' => 'online',
                'venue' => 'Online (Zoom)',
                'area' => 'Patna',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(10),
                'start_time' => '05:00 PM',
                'end_time' => '07:00 PM',
                'organizer' => 'Bihar Education Board',
                'featured_image' => 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800',
                'price_type' => 'free',
                'interested_count' => 2100,
                'is_active' => true,
            ],
            [
                'title' => 'Patna Marathon 2025',
                'description' => 'Annual city marathon with 5K, 10K, and 21K categories. Promote fitness and community wellness.',
                'event_category' => 'Sports & Fitness',
                'event_mode' => 'offline',
                'venue' => 'Gandhi Maidan, Patna',
                'area' => 'Gandhi Maidan',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(4),
                'start_time' => '05:30 AM',
                'end_time' => '10:00 AM',
                'organizer' => 'Patna Sports Authority',
                'featured_image' => 'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=800',
                'price_type' => 'paid',
                'price' => 300,
                'interested_count' => 2500,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Ganga Utsav 2025',
                'description' => 'Festival celebrating River Ganga with cultural programs, boat rides, and Ganga Aarti.',
                'event_category' => 'Cultural',
                'event_mode' => 'offline',
                'venue' => 'Gandhi Ghat, Patna',
                'area' => 'Patna',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(6),
                'start_time' => '04:00 PM',
                'end_time' => '09:00 PM',
                'organizer' => 'Tourism Department Bihar',
                'featured_image' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
                'price_type' => 'free',
                'interested_count' => 1800,
                'is_trending' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Entrepreneur Meet Patna',
                'description' => 'Networking evening for business owners and aspiring entrepreneurs. Share experiences and build connections.',
                'event_category' => 'Business & Networking',
                'event_mode' => 'offline',
                'venue' => 'The Maurya, Patna',
                'area' => 'Boring Road',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(27),
                'start_time' => '06:30 PM',
                'end_time' => '09:00 PM',
                'organizer' => 'Patna Entrepreneurs Club',
                'featured_image' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
                'price_type' => 'paid',
                'price' => 299,
                'interested_count' => 450,
                'is_active' => true,
            ],
            [
                'title' => 'Patna Food Festival 2025',
                'description' => 'Taste authentic Bihar and Patna cuisines. Food stalls, live cooking demos, and culinary competitions.',
                'event_category' => 'Food & Lifestyle',
                'event_mode' => 'offline',
                'venue' => 'Exhibition Ground, Patna',
                'area' => 'Patliputra',
                'city' => 'Patna',
                'event_date' => Carbon::now()->addDays(15),
                'start_time' => '11:00 AM',
                'end_time' => '10:00 PM',
                'organizer' => 'Bihar Tourism',
                'featured_image' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
                'price_type' => 'paid',
                'price' => 50,
                'interested_count' => 3500,
                'is_featured' => true,
                'is_trending' => true,
                'is_active' => true,
            ],
        ];

        foreach ($events as $eventData) {
            Event::create($eventData);
        }

        $this->command->info('Events seeded successfully!');
    }
}
