<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;

class EventsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Sample Recent Government Events for Patna / Bihar
     */
    public function run(): void
    {
        $events = [
            [
                'title' => 'National Kavi Samelan',
                'event_type' => 'kavi-samelan',
                'description' => 'Grand poetry gathering featuring celebrated poets, ghazals and cultural performances from across the state. Artists will present dohas, muktak and hindi kavita on the occasion.',
                'venue' => 'Kalidas Rangalaya',
                'address' => 'Frazer Road, Patna - 800001',
                'city' => 'Patna',
                'event_date' => now()->addDays(3)->toDateString(),
                'start_time' => '6:00 PM',
                'end_time' => '9:30 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Department of Art, Culture & Youth',
                'registration_url' => null,
                'contact_phone' => '0612-2223456',
                'contact_email' => 'culture@bihar.gov.in',
                'is_featured' => true,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'title' => 'Rojgar Mela & Job Interview Drive',
                'event_type' => 'job-mela',
                'description' => 'Government recruitment fair with walk-in interviews for 10th/12th pass and graduates. Stalls from state departments, PSUs and private companies offering on-the-spot job offers.',
                'venue' => 'Gandhi Maidan Hall',
                'address' => 'Gandhi Maidan, Patna - 800001',
                'city' => 'Patna',
                'event_date' => now()->addDays(7)->toDateString(),
                'start_time' => '10:00 AM',
                'end_time' => '5:00 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Bihar Skill Development Mission',
                'registration_url' => 'https://skillmissionbihar.org',
                'contact_phone' => '1800-345-6238',
                'contact_email' => 'rojgar@bsdm.bihar.gov.in',
                'is_featured' => true,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'title' => 'Doctors Health Camp',
                'event_type' => 'doctors-camp',
                'description' => 'Free health check-up and specialist consultation camp for senior citizens and all age groups. Facilities include blood pressure, sugar, ECG, dental and eye screening with free medicines.',
                'venue' => 'Patna Medical College & Hospital',
                'address' => 'Ashok Rajpath, Patna - 800004',
                'city' => 'Patna',
                'event_date' => now()->addDays(10)->toDateString(),
                'start_time' => '9:00 AM',
                'end_time' => '2:00 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Department of Health',
                'registration_url' => null,
                'contact_phone' => '0612-2671234',
                'contact_email' => 'healthhelp@bihar.gov.in',
                'is_featured' => true,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'title' => 'Industrial Investment Function',
                'event_type' => 'industrial',
                'description' => 'Industrial development convention and investment summit bringing together MSMEs, investors and department officials to discuss new industrial policies, incentives and business opportunities in Bihar.',
                'venue' => 'Bihar Industries Association',
                'address' => 'East Boring Canal Road, Patna - 800001',
                'city' => 'Patna',
                'event_date' => now()->addDays(12)->toDateString(),
                'start_time' => '11:00 AM',
                'end_time' => '4:30 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Department of Industries',
                'registration_url' => 'https://industries.bihar.gov.in',
                'contact_phone' => '0612-2211122',
                'contact_email' => 'industries@bihar.gov.in',
                'is_featured' => true,
                'is_active' => true,
                'display_order' => 4,
            ],
[
                'title' => 'IT Sector & Startup Conclave',
                'event_type' => 'it-sector',
                'description' => 'State IT conclave with tech workshops, startup showcases and panel discussions for students, professionals and entrepreneurs. Networking with industry leaders and incubation opportunities.',
                'venue' => 'Bihar State IT Hub (Beltron)',
                'address' => 'Shastri Nagar, Patna - 800023',
                'city' => 'Patna',
                'event_date' => now()->addDays(15)->toDateString(),
                'start_time' => '10:30 AM',
                'end_time' => '6:00 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Bihar State Electronics Development Corporation (Beltron)',
                'registration_url' => 'https://beltron.in',
                'contact_phone' => '0612-2282351',
                'contact_email' => 'event@beltron.in',
                'is_featured' => true,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'title' => 'State Education Convention',
                'event_type' => 'other',
                'description' => 'Education convention for board exam aspirants, teachers and parents. Sessions on new education policy, exam preparation strategies and career guidance by education department experts.',
                'venue' => 'Bihar State Museum Auditorium',
                'address' => 'Bailey Road, Patna - 800017',
                'city' => 'Patna',
                'event_date' => now()->addDays(20)->toDateString(),
                'start_time' => '10:00 AM',
                'end_time' => '3:00 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Department of Education',
                'registration_url' => null,
                'contact_phone' => '0612-2509456',
                'contact_email' => 'education@bihar.gov.in',
                'is_featured' => false,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'title' => 'State Digital India Awareness Camp',
                'event_type' => 'it-sector',
                'description' => 'Awareness camp on digital services, DigiLocker, UMANG and online government schemes. Free guidance for citizens on using e-governance portals and digital payments safely.',
                'venue' => 'Rajdhani Vatika, Kankarbagh',
                'address' => 'Kankarbagh Main Road, Patna - 800020',
                'city' => 'Patna',
                'event_date' => now()->addDays(25)->toDateString(),
                'start_time' => '11:00 AM',
                'end_time' => '4:00 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Department of Information Technology',
                'registration_url' => null,
                'contact_phone' => '1800-345-6325',
                'contact_email' => 'digital@bihar.gov.in',
                'is_featured' => false,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'title' => 'Kisan Krishi Mela (Farmer Fair)',
                'event_type' => 'other',
                'description' => 'Agricultural fair with stalls on modern farming techniques, seeds, irrigation equipment and government subsidy schemes. Technical sessionsand farmer-scientist interactions.',
                'venue' => 'Bihar Agricultural College Ground',
                'address' => 'Sabour, Bhagalpur Road, Patna - 800014',
                'city' => 'Patna',
                'event_date' => now()->addDays(30)->toDateString(),
                'start_time' => '9:00 AM',
                'end_time' => '5:00 PM',
                'organizer' => 'Bihar Government',
                'department' => 'Department of Agriculture',
                'registration_url' => null,
                'contact_phone' => '0612-2311198',
                'contact_email' => 'kisan@bihar.gov.in',
                'is_featured' => false,
                'is_active' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($events as $event) {
            Event::firstOrCreate(
                ['title' => $event['title'], 'event_date' => $event['event_date']],
                $event
            );
        }
    }
}